# Site settings
title: Stop The Spies - Launching soon - Spread the word
email: admin@stopthespies.org
description: "Stop The Spies is an Australian campaign against mass surveillance. Currently the campaign is looking to build momentum before launching in late September."
baseurl: ""
url: "https://stopthespies.org"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: css/_sass
